// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
<<<<<<< HEAD
    apiKey: 'AIzaSyDIy7335TFpZ2HZ9vlsiP1J_w0_AabIvWc',
    appId: '1:263281507170:android:2973b7b91e4c0020f6ca3b',
    messagingSenderId: '263281507170',
    projectId: 'smp-chat-5bb23',
    storageBucket: 'smp-chat-5bb23.firebasestorage.app',
  );

}
=======
    apiKey: 'AIzaSyBZYx77zvKIqFyYtZiArt4fcUnU2PG1hAg',
    appId: '1:951854646259:android:12e23892bcb93661a90886',
    messagingSenderId: '951854646259',
    projectId: 'smp-1-3a26e',
    storageBucket: 'smp-1-3a26e.firebasestorage.app',
  );
}
>>>>>>> 6f653a1dbc1a6fa0903d095bb8f923b67afcda73
